from ._classes.enums.CustomEnum import CustomEnum
from ._classes.Element import Element
from ._classes.tags.A import A
from ._classes.tags.Abbr import Abbr
from ._classes.tags.Address import Address
from ._classes.tags.Area import Area
from ._classes.tags.Article import Article
from ._classes.tags.Aside import Aside
from ._classes.tags.Audio import Audio
from ._classes.tags.B import B
from ._classes.tags.Base import Base
from ._classes.tags.BDI import BDI
from ._classes.tags.BDO import BDO
from ._classes.tags.Blockquote import Blockquote
from ._classes.tags.Body import Body
from ._classes.tags.BR import BR
from ._classes.tags.Button import Button
from ._classes.tags.Canvas import Canvas
from ._classes.tags.Caption import Caption
from ._classes.tags.Cite import Cite
from ._classes.tags.Code import Code
from ._classes.tags.Col import Col
from ._classes.tags.ColGroup import ColGroup
from ._classes.tags.Comment import Comment
from ._classes.tags.Data import Data
from ._classes.tags.DataList import DataList
from ._classes.tags.DD import DD
from ._classes.tags.Del import Del
from ._classes.tags.Details import Details
from ._classes.tags.DFN import DFN
from ._classes.tags.Dialog import Dialog
from ._classes.tags.Div import Div
from ._classes.tags.DL import DL
from ._classes.tags.DT import DT
from ._classes.tags.EM import EM
from ._classes.tags.Embed import Embed
from ._classes.tags.Fieldset import Fieldset
from ._classes.tags.FigCaption import FigCaption
from ._classes.tags.Figure import Figure
from ._classes.tags.Footer import Footer
from ._classes.tags.Form import Form
from ._classes.tags.H import H
from ._classes.tags.Head import Head
from ._classes.tags.Header import Header
from ._classes.tags.HR import HR
from ._classes.tags.HTML import HTML
from ._classes.tags.I import I
from ._classes.tags.IFrame import IFrame
from ._classes.tags.Img import Img
from ._classes.tags.Input import Input
from ._classes.tags.Ins import Ins
from ._classes.tags.Kbd import Kbd
from ._classes.tags.Label import Label
from ._classes.tags.Legend import Legend
from ._classes.tags.LI import LI
from ._classes.tags.Link import Link
from ._classes.tags.Main import Main
from ._classes.tags.Map import Map
from ._classes.tags.Mark import Mark
from ._classes.tags.Meta import Meta
from ._classes.tags.Meter import Meter
from ._classes.tags.Nav import Nav
from ._classes.tags.NoScript import NoScript
from ._classes.tags.Object import Object
from ._classes.tags.OL import OL
from ._classes.tags.OptGroup import OptGroup
from ._classes.tags.Option import Option
from ._classes.tags.Output import Output
from ._classes.tags.P import P
from ._classes.tags.Param import Param
from ._classes.tags.Picture import Picture
from ._classes.tags.Pre import Pre
from ._classes.tags.Progress import Progress
from ._classes.tags.Q import Q
from ._classes.tags.RP import RP
from ._classes.tags.RT import RT
from ._classes.tags.Ruby import Ruby
from ._classes.tags.S import S
from ._classes.tags.Samp import Samp
from ._classes.tags.Script import Script
from ._classes.tags.Section import Section
from ._classes.tags.Select import Select
from ._classes.tags.Small import Small
from ._classes.tags.Source import Source
from ._classes.tags.Span import Span
from ._classes.tags.Strong import Strong
from ._classes.tags.Style import Style
from ._classes.tags.Sub import Sub
from ._classes.tags.Summary import Summary
from ._classes.tags.Sup import Sup
from ._classes.tags.SVG import SVG
from ._classes.tags.Table import Table
from ._classes.tags.TBody import TBody
from ._classes.tags.TD import TD
from ._classes.tags.Template import Template
from ._classes.tags.TextArea import TextArea
from ._classes.tags.TFoot import TFoot
from ._classes.tags.TH import TH
from ._classes.tags.THead import THead
from ._classes.tags.Time import Time
from ._classes.tags.Title import Title
from ._classes.tags.TR import TR
from ._classes.tags.Track import Track
from ._classes.tags.U import U
from ._classes.tags.UL import UL
from ._classes.tags.Var import Var
from ._classes.tags.Video import Video
from ._classes.tags.WBR import WBR
